name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  webclient:
    name: PomoThings Web Client
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./webclient

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: CI=true npm test

  server:
    name: PomoThings Server
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: CI=true npm test
